# Generated by Django 2.2.4 on 2022-05-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one_to_many_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojos',
            name='desc',
            field=models.CharField(default=2, max_length=2),
            preserve_default=False,
        ),
    ]
